spring.datasource.url=jdbc:postgresql://localhost:5432/employee_sys
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=5e40a81da134840fa4a57101c531ae29baa4a2c46f3357ac6a183320b2b42cda
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_APP_USERNAME}
spring.mail.password=${Gmail_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#backend.origin=8080
backend.origin=http://localhost:5173
#spring.sql.init.mode=always






